name: delpoy
on:
  workflow_run:
    workflows: ["build"]
    types: 
      - completed
jobs:
  delpoy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote deploy
        uses: docker://evaneos/ssh-action:0.1.0
        with: 
          hosts: 47.99.66.0
          user: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          commands: |
            have=$(docker inspect --format='{{.Name}}' $(docker ps -aq) |grep static  | cut -d"/" -f2)
            if [[ "$have" == static ]]; then \
              docker container stop static; \
              docker container rm static; \
            fi
            docker rmi registry.cn-hongkong.aliyuncs.com/littledian/static:latest
            docker run \
              -p 3002:80 \
              --name static \
              --restart always \
              -d registry.cn-hongkong.aliyuncs.com/littledian/static:latest
